security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
            logout:
                path:       logout
                target:     homepage
            logout_on_user_change: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
